### ISSUE TITLE
运行程序点击整理报错-list index out of range

### ISSUE THREAD

**Issue by udpsec** [wysec2020/vulnReport#2]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python37\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "main.py", line 168, in zhengli_awvs
    (category, venus_list) = vuln_awvs.zhengli(file, info_flag)
  File "C:\Users\vulnReport\vuln_awvs.py", line 31, in zhengli
    baseurl = awvs_baseURL[0]+"//"+awvs_baseURL[2]
IndexError: list index out of range

**Comment by udpsec** [comment]
![image](https://user-images.githubusercontent.com/10917718/85124668-de07a600-b25c-11ea-8dd6-5f93c68bd1fe.png)
